### ISSUE TITLE
Memory Leak in guaranteed publisher

### ISSUE THREAD

**Issue by nasai1** [SolaceSamples/solace-samples-python#34] opened 2023-02-21 11:21 UTC
Hi Team,

There has been memory leak in Guaranteed publisher while using in google cloud function. Here are trace malloc top 20 rows from production code -

ver - Python 3.7

[ Top 20 ]
/layers/google.python.runtime/python/lib/python3.7/threading.py:238: size=8097 KiB, count=28908, average=287 B
 /layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:882: size=4456 KiB, count=26002, average=175 B
/layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:865: size=4310 KiB, count=23392, average=189 B
/layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:873: size=4086 KiB, count=24142, average=173 B
/layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:856: size=3925 KiB, count=22286, average=180 B
 /layers/google.python.runtime/python/lib/python3.7/threading.py:500: size=2276 KiB, count=49214, average=47 B
/layers/google.python.runtime/python/lib/python3.7/queue.py:206: size=1435 KiB, count=4249, average=346 B
/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py:55: size=1340 KiB, count=15957, average=86 B
/layers/google.python.runtime/python/lib/python3.7/threading.py:219: size=1250 KiB, count=9787, average=131 B
/layers/google.python.runtime/python/lib/python3.7/threading.py:348: size=1072 KiB, count=2079, average=528 B
/layers/google.python.runtime/python/lib/python3.7/threading.py:365: size=967 KiB, count=1875, average=528 B
/layers/google.python.runtime/python/lib/python3.7/threading.py:222: size=809 KiB, count=10357, average=80 B
 /layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:907: size=798 KiB, count=3714, average=220 B
/layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:905: size=798 KiB, count=3714, average=220 B
/layers/google.python.runtime/python/lib/python3.7/json/decoder.py:353: size=768 KiB, count=5621, average=140 B
 /layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:912: size=722 KiB, count=5992, average=123 B
/layers/google.python.pip/pip/lib/python3.7/site-packages/google/api_core/retry.py:191: size=690 KiB, count=4203, average=168 B
/layers/google.python.runtime/python/lib/python3.7/threading.py:221: size=670 KiB, count=8578, average=80 B
 /layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/messaging_service.py:537: size=609 KiB, count=1857, average=336 B
 /layers/google.python.pip/pip/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py:409: size=609 KiB, count=1856, average=336 B

**Comment by TamimiGitHub** [comment] 2023-02-21 20:14
Hey @nasai1 - thanks for opening the issue. We have not seen this problem before or was able to reproduce it locally. I do however have a couple of questions/comments

- What version of the Solace Pubsub+ Python API are you using? It's not clear from your logs what version of the API is used. You can see the latest version of the API on [PyPi](https://pypi.org/project/solace-pubsubplus/). If you are defining an older version of the API can you please upgrade and try again. 
- We have not worked with Google Python Runtime, do you have any further details on whether this is just a pythonc wrapper?
- Can you provide more details on the repro steps for this? Does it happen right away or after some time? Is it reproducible on your local machine or you've only observed this with Google Cloud functions? Are you modifying the Guaranteed publisher sample or running it as is?

Any extra details on code, reproducible steps, environments, and versions will help with debugging this issue. 

Thanks!

**Comment by nasai1** [comment] 2023-02-22 06:30
Hi @TamimiGitHub : 

1. Here is my requirement.txt file -
```
httpx[http2]==0.23.0
google-cloud-firestore==2.3.4
solace-pubsubplus==1.2.0
google-cloud-secret-manager==2.8.0
google-cloud-logging==3.0.0
urllib3==1.26.3
lxml==4.8.0
```
2. hers is the snapshot of code (filename - PublisherSolace.py) -
```
import traceback
import logging
import threading
import re
import main as main
import RequestHelper as integrationHelper

from solace.messaging.messaging_service import MessagingService, ReconnectionListener, ReconnectionAttemptListener, ServiceInterruptionListener, RetryStrategy, ServiceEvent
from solace.messaging.publisher.persistent_message_publisher import PersistentMessagePublisher
from solace.messaging.publisher.persistent_message_publisher import MessagePublishReceiptListener
from solace.messaging.resources.topic import Topic
#from solace.messaging.errors.pubsubplus_client_error import PubSubPlusClientError

# Inner classes for error handling
class ServiceEventHandler(ReconnectionListener, ReconnectionAttemptListener, ServiceInterruptionListener):
    def on_reconnected(self, e: ServiceEvent):
        print("\non_reconnected")
        print(f"Error cause: {e.get_cause()}")
        print(f"Message: {e.get_message()}")
    
    def on_reconnecting(self, e: "ServiceEvent"):
        print("\non_reconnecting")
        print(f"Error cause: {e.get_cause()}")
        print(f"Message: {e.get_message()}")

    def on_service_interrupted(self, e: "ServiceEvent"):
        print("\non_service_interrupted")
        print(f"Error cause: {e.get_cause()}")
        print(f"Message: {e.get_message()}")

class MessageReceiptListener(MessagePublishReceiptListener):
    def __init__(self):
        self._receipt_count = 0

    @property
    def receipt_count(self):
        return self._receipt_count

    def on_publish_receipt(self, publish_receipt: 'PublishReceipt'):
        lock = threading.Lock() # lock object that is not owned by any thread. Used for synchronization and counting the
        with lock:
            self._receipt_count += 1
            print(f"\npublish_receipt:\n {self.receipt_count}\n")
            
def publish_message(solmessageHeader, bu_code, bu_type, message ):            

    TOPIC_NAME = main.SOLACE_TOPIC + f'/' + bu_type + f'/' + bu_code

    message_id = solmessageHeader["solmessageId"]
    publish_time = solmessageHeader["solpublishtime"]
    message_type = solmessageHeader["solmessagetype"]
    test_message_id = solmessageHeader["soltestmessageId"]
    test_case_id = solmessageHeader["soltestCaseID"]
    dmq_eligible = solmessageHeader["soldmqEligible"].capitalize()
    sol_error = 'NA'
    
    if message_id.casefold() == "NA".casefold():
        message_id = ''
        
    if publish_time.casefold() == "NA".casefold():
        publish_time = ''
    
    #receipt_listener = MessageReceiptListener()

    try:

        # Broker Config. Note: Could pass other properties Look into
        broker_props = integrationHelper.getSolaceBrokerDetails(dmq_eligible)

        # Build A messaging service with a reconnection strategy of 3 retries over an interval of 3 seconds
        # Note: The reconnections strategy could also be configured using the broker properties object
        messaging_service = MessagingService.builder().from_properties(broker_props)\
                            .with_reconnection_retry_strategy(RetryStrategy.parametrized_retry(3,3))\
                            .build()

        # Blocking connect thread
        messaging_service.connect()
        print(f'Messaging Service connected? {messaging_service.is_connected}')

        # Event Handling for the messaging service
        service_handler = ServiceEventHandler()
        messaging_service.add_reconnection_listener(service_handler)
        messaging_service.add_reconnection_attempt_listener(service_handler)
        messaging_service.add_service_interruption_listener(service_handler)

        # Create a persistent message publisher and start it
        publisher: PersistentMessagePublisher = messaging_service.create_persistent_message_publisher_builder().build()
        publisher.start()
        print('PERSISTENT publisher started')

        # set a message delivery listener to the publisher
        receipt_listener = MessageReceiptListener()
        publisher.set_message_publish_receipt_listener(receipt_listener)

        # Prepare the destination topic
        topic = Topic.of(TOPIC_NAME)

        try:  
            
            if message_type.casefold() == "Simulate_OK".casefold():
            
                # Prepare outbound message payload and body
                outbound_msg = messaging_service.message_builder() \
                        .with_application_message_id(message_id) \
                        .with_property("test-message-id", test_message_id) \
                        .with_property("Message-Type", message_type) \
                        .with_property("test-case-id", test_case_id) \
                        .with_property("solace.messaging.message.persistent.dmq-eligible", eval(dmq_eligible)) \
                        .build(f'{message}')
                
            else:
                
                # Prepare outbound message payload and body
                outbound_msg = messaging_service.message_builder() \
                        .with_application_message_id(message_id) \
                        .with_property("solace.messaging.message.persistent.dmq-eligible", eval(dmq_eligible)) \
                        .build(f'{message}')

            publisher.publish(outbound_msg, topic)
            #time.sleep(2)
            print(f'PERSISTENT publish message is successful... Topic: [{topic.get_name()}]')
                

        except Exception as ex:
            
            logging.error("Error occurred while publishing: " + str(traceback.format_exc().replace("\n","")))
            sol_error = format(ex)
            return sol_error
            
            
            
        finally:
            #print(f'\nDelivery receipt count: {receipt_listener.receipt_count}\n')
            print('\nTerminating Publisher')
            publisher.terminate()
            print('\nDisconnecting Messaging Service')
            messaging_service.disconnect()
            if sol_error != 'NA':
                return sol_error
            return 'OK'

    except Exception as ex:
        logging.error("Error occurred while connecting Solace: " + str(traceback.format_exc().replace("\n","")))
        sol_error = format(ex)
        return sol_error
            

def getSolaceErrorDetails(solaceErrResponse):
    """ 
    Following function is used for setting errorCode, errorMessage, errorBody based on response received from Solace
    """
    try:
        str_search = '{'
        if (solaceErrResponse.find(str_search)) != -1 :
            
            pattern  =  ".*" + str_search 
            str_sol_error = re.sub(pattern, str_search, solaceErrResponse )
            str_sol_error_repl = eval(str_sol_error)
            errorCode = '60' + str(str_sol_error_repl['error_info_sub_code'])
            errorMessage = str(str_sol_error_repl['sub_code'])
            errorBody = str(str_sol_error_repl['error_info_contents'])

            return errorCode, errorMessage, errorBody
        else:
        
            errorCode = '6000'
            errorMessage = solaceErrResponse
            errorBody = solaceErrResponse
            
            return errorCode, errorMessage, errorBody
            
    except Exception as ex:
        raise ex
```

3. for reproducing - as this is happening when we have huge load in prod (25-30 msg/sec) on Cloud function Generation 1 with 1 GB (.5 vcpu) of memory and unlimited instance count. after the deployment of new version, memory starts to go up by up till its reaches to 1 GB boundary limit.
![image](https://user-images.githubusercontent.com/70207318/220532231-5c275973-8bf2-4b01-953b-fa0b79914f86.png)
![image](https://user-images.githubusercontent.com/70207318/220532465-6cae8b66-8c5e-4040-85ec-d72dafb03605.png)


4. what we have done so far - we shift global threading. Lock to local scope as you can see there are lots of threading.py in top 20 rows as well as solace. Session lines which are taking more memory. but after deployment in prod, it did not work.
5. we also remove publishing part to solace from application and did test in non prod env and can see the memory is in same line (no memory leaks). 
![image](https://user-images.githubusercontent.com/70207318/220541448-8209ecaa-edef-4c11-b0cf-f447b86f1037.png)

**Comment by TamimiGitHub** [comment] 2023-02-22 17:06
Hey @nasai1 - I have edited your comment to include code in code blocks using ``` for easier readability. Just an FYI for future issues.

Thanks for providing the details. I will take a deeper look into the information you provided. As a starter tho before we delve into it, can you please: 

- Update the version of the solace API and confirm if you are still seeing the same issue? As of today, from the link i sent you earlier, the latest version of the API is 1.4.1. If you still see the same issue, a new stack trace would be needed. 

I'll get back to this issue with more details if anything comes up

**Comment by nasai1** [comment] 2023-02-23 04:20
Hi @TamimiGitHub , yes i have changed solace API 1.2.0 to 1.4.1 or 1.4.0 but i have connection timeout issue when terminating the publisher and too many client username issue though we have 500 client profile set.

Error message - Message: 'Solace Error'
Arguments: ("{'caller_description': 'do_connect', 'return_code': 'Not ready', 'sub_code': 'SOLCLIENT_SUBCODE_CONTROL_OTHER', 'error_info_sub_code': 27, 'error_info_contents': 'Too Many Connections For Client-Username'}",)

![image](https://user-images.githubusercontent.com/70207318/220820617-c82f99e6-cf3f-4a0f-b956-d6045c8205e3.png)


After rollbacking to 1.2.0 , now i don't have this connectivity error but still memory high consumption.
![image](https://user-images.githubusercontent.com/70207318/220821256-efad5479-464e-4070-885a-a1e35fb5a81c.png)

**Comment by nasai1** [comment] 2023-03-06 06:19
Hi team, Any suggestions till far ?

**Comment by TamimiGitHub** [comment] 2023-03-06 15:11
Hey @nasai1 - I would suggest staying with the latest Python API available since that fixed your original issue. Regarding your number of connections issue - There are a couple of things you can do: 

- Check your client profile on your broker that reflects the credentials used to connect to the broker. The client-profile is configured with a Max # Connections per client-username
- Provide more logs and details from your end. Are you able to run your configuration locally and get more application level logs? Note you can set the log level to `DEBUG` to get further logs from your python application?

I would also suggest we close this issue since the original problem of memory leak has been solved with an API update. And you can open another issue with regards to your max number of connections

**Closed as completed by TamimiGitHub** 2023-03-06 15:11 UTC
